[package]
name = "$PROJ_NAME$_glue"
version = "1.0.0"
edition = "2021"

[dependencies]
brinicle_glue = "1.0"
libc = "0.2"
smallvec = "0.6"

[dependencies.$PROJ_NAME$_kernel]
path = "../kernel"

[lib]
crate-type = ["staticlib"]
name = "$PROJ_NAME$_glue"
