[package]
name = "$PROJ_NAME$_kernel"
version = "1.0.0"
edition = "2018"

[dependencies]
enum_primitive = "*"
itertools = "0.4.4"
lazy_static = "1.3.0"

[dependencies.brinicle_kernel]
path = "../../../icicle-basics/rust/kernel"


