[package]
name = "brinicle_voices"
version = "1.0.0"
license = "MIT"
authors = ["Russell McClellan <russell.mcclellan@gmail.com>"]
edition = "2018"
repository = "https://github.com/russellmcc/brinicle"
description = "Voice allocation logic used in brinicle."

[dependencies]
bit-set = "^0.2.0"