[package]
name = "brinicle_pitch"
version = "1.0.0"
license = "MIT"
authors = ["Russell McClellan <russell.mcclellan@gmail.com>"]
edition = "2018"
repository = "https://github.com/russellmcc/brinicle"
description = "Pitch calculation utilities used in brinicle."

[dependencies]
log = "^0.3.2"