[package]
name = "brinicle_midi"
version = "1.0.0"
license = "MIT"
authors = ["Russell McClellan <russell.mcclellan@gmail.com>"]
edition = "2018"
repository = "https://github.com/russellmcc/brinicle"
description = "MIDI parsing utilities used in brinicle."

[dependencies]
